# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-22 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('relevant_symptoms', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'disease_helper',
            },
        ),
        migrations.CreateModel(
            name='SymptomHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('relevant_diseases', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'symptom_helper',
            },
        ),
    ]
