# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasedetailinfo',
            old_name='examination',
            new_name='clinical_examination',
        ),
        migrations.AddField(
            model_name='diseasedetailinfo',
            name='distinguish',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diseasedetailinfo',
            name='nurse',
            field=models.TextField(null=True),
        ),
    ]
