# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0002_auto_20160524_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('cause_of_symptom', models.TextField(null=True)),
                ('diagnostic_details', models.TextField(null=True)),
            ],
            options={
                'db_table': 'symptom_detail_info',
            },
        ),
    ]
