# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0003_symptomdetailinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '39_news_category',
            },
        ),
        migrations.CreateModel(
            name='NewsHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, unique=True)),
                ('category_id', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=200, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': '39_news_helper',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('newshelper', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stalk.NewsHelper')),
                ('title', models.CharField(max_length=200, null=True)),
                ('time', models.CharField(max_length=50, null=True)),
                ('source_website', models.CharField(max_length=200, null=True)),
                ('source_website_link', models.CharField(max_length=200, null=True)),
                ('source_author', models.CharField(max_length=200, null=True)),
                ('summary', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'db_table': '39_news',
            },
        ),
    ]
