# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalk', '0003_symptomdetailinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFDADrugInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.IntegerField(unique=True)),
                ('approval_num', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('en_name', models.CharField(max_length=255, null=True)),
                ('trade_name', models.CharField(max_length=255, null=True)),
                ('dosage_forms', models.CharField(max_length=255, null=True)),
                ('norm', models.CharField(max_length=255, null=True)),
                ('producer', models.CharField(max_length=255, null=True)),
                ('product_address', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('origin_approval_num', models.CharField(max_length=255, null=True)),
                ('approval_date', models.CharField(max_length=255, null=True)),
                ('drug_based_code', models.CharField(max_length=255, null=True)),
                ('remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cfda_drug_info',
            },
        ),
    ]
